# Generated by Django 4.1.2 on 2022-10-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='budget',
            field=models.IntegerField(default=15000),
        ),
        migrations.AddField(
            model_name='video',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
