# Generated by Django 4.1.2 on 2022-10-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_application', '0003_video_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='cur_id',
            field=models.CharField(choices=[('USD', 'Dollar'), ('EUR', 'Euro'), ('RUB', 'Rubles')], default='USD', max_length=3),
        ),
    ]
