# Generated by Django 4.1.2 on 2022-10-24 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_application', '0005_alter_video_budget_alter_video_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='director',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='budget',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
