# Generated by Django 4.1.2 on 2022-10-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_application', '0009_actor_video_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='direct_slug',
            field=models.SlugField(default=''),
        ),
    ]
