# Generated by Django 4.1.2 on 2022-10-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_application', '0010_director_direct_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='actor_slug',
            field=models.SlugField(default=''),
        ),
    ]
