# Generated by Django 4.1.2 on 2022-10-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_application', '0012_alter_video_actors_alter_video_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='', null=True),
        ),
    ]
